Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using mvc_project.Models;

namespace mvc_project.Controllers
{
    public class CarController : Controller
    {
        private readonly MainDBContext  _dbContext;          
     
        private readonly ILogger<HomeController> _logger;
        

        public CarController(MainDBContext context, ILogger<HomeController> logger)
        {
            _logger = logger;
            _dbContext = context;
        }

        public List<Car> GetCars<Car>() where Car : class
        {  
            {
                return _dbContext.Set<Car>().ToList();
            }
        }

        public List<User> GetAllUsers<User>() where User : class
        {    
            {
                return _dbContext.Set<User>().ToList();
            }
        }

        public IActionResult Index(int userId)
        {
            // User tempUser = new User{EmailAddress = "firstylasty@test.com", FirstName = "JrFirsty", LastName = "Lasty", Password = "testPass123", SecretQuestionFirst = "First Pet", SecretQuestionSecond = "First School"};
            // _dbContext.Users.Add(tempUser);
            // _dbContext.SaveChanges();
            ViewBag.MyCars =  GetCars<Car>().FindAll(car => car.UserId == ((userId != 0) ? userId : 1)).OrderBy(car => car.Year);
            var users = GetAllUsers<User>();
            ViewBag.User = users.Find(user => user.Id == 1);
            return View();
        }

        public IActionResult NewCarView()
        {
            return View();
        }

        public IActionResult AddNewCar(Car car)
        {
            _dbContext.Cars.Add(car);
            _dbContext.SaveChanges();
            return RedirectToActionPermanent("Index", new{Id = 1});
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HistoryController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using mvc_project.Models;
using Microsoft.EntityFrameworkCore;

namespace mvc_project.Controllers
{
    public class HistoryController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly MainDBContext _dbContext;

        


        public HistoryController(MainDBContext dbContext, ILogger<HomeController> logger)
        {
            _logger = logger;
            _dbContext = dbContext;
        }

        public List<ServiceRecord> GetAllServiceRecords<ServiceRecord>() where ServiceRecord : class
        {     
            {
                return _dbContext.Set<ServiceRecord>().ToList();
            }
        }

        public IActionResult Index()
        {
            string carAndServiceRecordQuery = "SELECT service.\"Id\", service.\"Date\", car.\"Year\", car.\"Make\", car.\"Model\", service.\"Mileage\", service.\"Description\", service.\"EstimateCost\" FROM \"Cars\" car JOIN \"ServiceRecords\" service ON car.\"Id\" = service.\"VehicleId\"";
            ViewBag.ServiceRecordsHistory =  _dbContext.ServiceRecordsHistory.FromSqlRaw(carAndServiceRecordQuery).ToList();
            ViewBag.Cars = _dbContext.Cars;
           
            return View();
        }

        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ServiceRecordController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using mvc_project.Models;
using mvc_project.Controllers;


namespace mvc_project.Controllers
{
    public class ServiceRecordController : Controller
    {
        private readonly ILogger<ServiceRecordController> _logger;
        private readonly MainDBContext _dbContext;
       

        public ServiceRecordController(MainDBContext dbContext, ILogger<ServiceRecordController> logger)
        {
            _logger = logger;
            _dbContext = dbContext;
        }
        public List<ServiceRecord> GetAllServiceRecords<ServiceRecord>() where ServiceRecord : class
        {
            {
                return _dbContext.Set<ServiceRecord>().ToList();
            }
        }

         public List<Car> GetAllCars<Car>() where Car : class
        {
            {
                return _dbContext.Set<Car>().ToList();
            }
        }

        public IActionResult Index()
        {
            return View();
        }
    
        public IActionResult GetServiceRecords(int Id)
        { 
            ViewBag.Car = GetAllCars<Car>().Find(car => car.Id == Id);
            ViewBag.ServiceRecords = GetAllServiceRecords<ServiceRecord>().Where(i => i.VehicleId == Id);
            return View();
        }


        public IActionResult NewServiceRecord(ServiceRecord newRecord)
        { 
            _dbContext.ServiceRecords.Add(newRecord);
            _dbContext.SaveChanges();
            return RedirectToAction("GetServiceRecords", new { id = newRecord.VehicleId }); //Going back to service record grid.
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mvc_project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @* <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Rider Catalog</a> *@
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index" >Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="Index" >Vehicles</a>
                        </li>
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="NewCarView">New Vehicle</a>
                        </li> *@
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ServiceRecord" asp-action="NewServiceRecord">New Service Record</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="History" asp-action="Index">History</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="body-container" style="width: 80vw; margin: 0vw 10vw 0vw;">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Burak Kocak <a asp-area="" asp-controller="Home" asp-action="Privacy">Catalog</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>